services:
  library:
    depends_on:
      - postgres
    build: .
    ports:
      - "8080:8080"
    restart: always
  postgres:
    restart: always
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=online_library